version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ~/customer_feedback/rabbitmq/data/:/var/lib/rabbitmq/
      - ~/customer_feedback/rabbitmq/log/:/var/log/rabbitmq
    networks:
      - rabbitmq_net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.4.0
    container_name: 'elasticsearch'
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9300:9300
      - 9200:9200
    volumes:
      - ~/customer_feedback/elasticsearch/data/:/var/lib/elasticsearch/data/
    networks:
      - elasticsearch_net

networks:
  rabbitmq_net:
    driver: bridge
  elasticsearch_net:
    driver: bridge
